import type { Metadata } from "next";
import { Nunito, Montserrat, Sacramento } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/navbar";
import Footer from "@/components/layout/footer";

const nuntino = Nunito({
  variable: "--font-nuntino",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const sacramento = Sacramento({
  variable: "--font-sacramento",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Malin Rydefalk",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nuntino.variable} ${montserrat.variable} ${sacramento.variable} antialiased`}
      >
        <Navbar />
        <main className="content-grid">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
